profile: null
region: us-east-1
versioning: false
default_alias: null
clean_build: false
configuration:
  name: alexa-sqs
  runtime: python2.7
  role: arn:aws:iam::180047737375:role/lambda_basic_execution
  handler: lambda_function.lambda_handler
  description: Send message to SQS to controll RasPi through alexa.
  timeout: 10
  memory_size: 128
